---
apiVersion: v1
kind: Service
metadata:
  name: crdb
spec:
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      name: http
    - protocol: TCP
      port: 26257
      targetPort: 26257
      name: crdb
---
apiVersion: v1
kind: Endpoints
metadata:
  name: crdb
subsets:
  - addresses:
      - ip: 192.168.4.50
      - ip: 192.168.4.60
      - ip: 192.168.4.70
    ports:
      - port: 8080
        name: http
      - port: 26257
        name: crdb
