podAnnotations:
  consul.hashicorp.com/connect-inject: 'true'

env:
  - name: POSTGRES_PASSWORD
    value: depscloud
  - name: POSTGRES_USER
    value: depscloud
  - name: POSTGRES_DB
    value: depsclouddb
