apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  namespace: networking
  name: traefik
spec:
  releaseName: traefik
  chart:
    repository: https://kubernetes-charts.storage.googleapis.com/
    name: traefik
    version: 1.86.2
  values:
    kubernetes:
      ingressClass: traefik
